/*
Storybook: Open Source software for novelists and authors.
Copyright (C) 2008 - 2012 Martin Mustun

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package storybook.model.hbn.entity;

import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.w3c.dom.Node;

import storybook.i18n.I18N;

/**
 * Gender generated by hbm2java
 * @hibernate.class
 *   table="GENDER"
 */
public class Gender extends AbstractEntity {

	private String name;
	private Integer childhood;
	private Integer adolescence;
	private Integer adulthood;
	private Integer retirement;
	private String icone;

	public Gender() {
		childhood = 12;
		adolescence = 6;
		adulthood = 47;
		retirement = 14;
	}

	public Gender(String name, Integer childhood, Integer adolescence,
			Integer adulthood, Integer retirement) {
		this.name = name;
		this.childhood = childhood;
		this.adolescence = adolescence;
		this.adulthood = adulthood;
		this.retirement = retirement;
	}

	@Override
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getChildhood() {
		return this.childhood;
	}

	public void setChildhood(Integer childhood) {
		this.childhood = childhood;
	}

	public Integer getAdolescence() {
		return this.adolescence;
	}

	public void setAdolescence(Integer adolescence) {
		this.adolescence = adolescence;
	}

	public Integer getAdulthood() {
		return this.adulthood;
	}

	public void setAdulthood(Integer adulthood) {
		this.adulthood = adulthood;
	}

	public Integer getRetirement() {
		return this.retirement;
	}

	public void setRetirement(Integer retirement) {
		this.retirement = retirement;
	}

	public boolean isMale() {
		return id == 1;
	}

	public boolean isFemale() {
		return id == 2;
	}

	@Override
	public Icon getImageIcon() {
		if (isMale()) {
			return I18N.getIcon("icon.small.man");
		} else if (isFemale()) {
			return I18N.getIcon("icon.small.woman");
		} else if (getIcone()!=null) {
			return new ImageIcon(getIcone());
		}
		return I18N.getIcon("icon.small.person");
	}
	
	public Icon getIcon(int h,int l) {
		if (isMale()) {
			return I18N.getIcon("icon.small.man");
		} else if (isFemale()) {
			return I18N.getIcon("icon.small.woman");
		} else if (getIcone()!=null) {
			return (I18N.resizeIcon(new ImageIcon(getIcone()),new Dimension(h,l)));
		}
		return I18N.getIcon("icon.small.person");
	}
	
	public void setIcon(String str) {
		icone=str;
	}
	
	public String getIcon() {
		return(icone);
	}
	
	public void setIcone(String str) {
		icone=str;
	}
	
	public String getIcone() {
		return(icone);
	}

	@Override
	public String toString() {
		return getName();
	}

	@Override
	public String toCsv(String quoteStart,String quoteEnd, String separator) {
		StringBuilder b=new StringBuilder();
		b.append(quoteStart).append(getId().toString()).append(quoteEnd).append(separator);
		b.append(quoteStart).append(getName()).append(quoteEnd).append(separator);
		b.append(quoteStart).append(getClean(getChildhood())).append(quoteEnd).append(separator);
		b.append(quoteStart).append(getClean(getAdolescence())).append(quoteEnd).append(separator);
		b.append(quoteStart).append(getClean(getAdulthood())).append(quoteEnd).append(separator);
		b.append(quoteStart).append(getClean(getRetirement())).append(quoteEnd).append(separator);
		b.append(quoteStart).append(getIcone()).append(quoteStart).append("\n");
		return(b.toString());
	}
	
	@Override
	public String toHtml() {
		return(toCsv("<td>","</td>","\n"));
	}
	
	@Override
	public String toText() {
		return(toCsv("","","\t"));
	}
	
	@Override
	public String toXml() {
		StringBuilder b=new StringBuilder();
		b.append(xmlTab(1)).append("<gender \n");
		b.append(xmlCommon());
		b.append(xmlAttribute("name", getName()));
		b.append(xmlAttribute("childhood", getClean(getChildhood())));
		b.append(xmlAttribute("adolescence", getClean(getAdolescence())));
		b.append(xmlAttribute("adulthood", getClean(getAdulthood())));
		b.append(xmlAttribute("retirement", getClean(getRetirement())));
		b.append(xmlAttribute("icone", getIcone()));
		b.append(xmlTab(2)).append(" />\n");
		return(b.toString());
	}
	
	public static Gender fromXml(Node node) {
		Gender p=new Gender();
		p.setId(getXmlLong(node,"id"));
		p.setName(getXmlString(node,"name"));
		p.setChildhood(getXmlInteger(node,"childhood"));
		p.setAdolescence(getXmlInteger(node,"adolescence"));
		p.setAdulthood(getXmlInteger(node,"adulthood"));
		p.setRetirement(getXmlInteger(node,"retirement"));
		p.setIcone(getXmlString(node,"icone"));
		return(p);
	}

	@Override
	@SuppressWarnings("EqualsWhichDoesntCheckParameterClass")
	public boolean equals(Object obj) {
		if (!super.equals(obj)) {
			return false;
		}
		Gender test = (Gender) obj;
		boolean ret = true;
		ret = ret && equalsStringNullValue(name, test.getName());
		ret = ret && equalsIntegerNullValue(childhood, test.getChildhood());
		ret = ret && equalsIntegerNullValue(adolescence, test.getAdolescence());
		ret = ret && equalsIntegerNullValue(adulthood, test.getAdulthood());
		ret = ret && equalsIntegerNullValue(retirement, test.getRetirement());
		return ret;
	}

	@Override
	public int hashCode() {
		int hash = super.hashCode();
		hash = hash * 31 + (name != null ? name.hashCode() : 0);
		hash = hash * 31 + (childhood != null ? childhood.hashCode() : 0);
		hash = hash * 31 + (adolescence != null ? adolescence.hashCode() : 0);
		hash = hash * 31 + (adulthood != null ? adulthood.hashCode() : 0);
		hash = hash * 31 + (retirement != null ? retirement.hashCode() : 0);
		return hash;
	}
}
